# Site
title:              Massively
bio:                'Massively'
description:        "Massively"
locale:             ko_KR
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    comments: true
    layout: post
    author:
# Jekyll
permalink:          /blog/:title/ #avoid duplicate _site/blog/ directory because `permalink` on befor line.
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   https-socoolbear-github-io

# Social
analytics-id:       "socoolbear"
twitter:            socoolbear
facebook:           socoolbear
instagram:          socoolbear
github:             socoolbear

# personal
location:           Gwanak-gu, Seoul, Republic of Korea
phone:              xxx
email:              socoolbear@gmail.com

# Gems
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page:num/"

jekyll-mentions:
    base_url: https://github.com/socoolbear

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
